### ISSUE TITLE
govc not found

### ISSUE THREAD

**Issue by dsimmons5280** [sparameswaran/nsx-t-gen#19]
Getting this error when it tries to install the ovas for the 2.2 branch

/tmp/build/647f336c/nsx-t-gen-pipeline/functions/deploy_ova_using_govc.sh: line 170: govc: command not found
No JSON object could be decoded
Using VM options for ova upload
/tmp/build/647f336c/nsx-t-gen-pipeline/functions/deploy_ova_using_govc.sh: line 38: govc: command not found

govc is getting installed in the container but the $PATH is not getting updated with /root/go/bin and govc is not copied into /usr/bin as specified in the dockerfile so deploy_ova_using_govc.sh can't find it

**Comment by vsential** [comment]
I am receiving the same.

**Comment by sparameswaran** [comment]
I dont know how docker image for v2.2 changed but I have pushed a fix yesterday to ensure the govc is part of the /usr/bin and /usr/local/bin path in the latest docker image. Try to do a refresh/retry of the install task or if its still using older cached docker image, then destroy the pipeline (nothing has run really so far) and register the pipeline and run it again.

**Comment by dsimmons5280** [comment]
we pulled the v2.2 image again and destroyed the pipeline and then reflew, we are still getting the same error

**Comment by sparameswaran** [comment]
@dsimmons5280 : Are you using [canned-pks](https://github.com/pivotalservices/canned-pks) where the docker image gets saved ahead in a minio/s3 compatible blob store for offline use? if so, you would have to refresh the saved docker image for nsx-t-gen-worker in the blobstore. If not using canned pks, try to run docker locally and check for existence of govc using find command against root (/):
`docker run --rm -it nsxedgegen/nsx-t-gen-worker:v2.2 bash -c find / -name govc | grep bin/govc`  
You can try to use fly hijack on the failed container and rerun the same find and see if its containing it or not.

I suspect its still using the older cached docker image and not the latest one. Wish I can jump on a remote zoom or other session to help faster.

**Comment by dsimmons5280** [comment]
@sparameswaran we are using [canned-pks](https://github.com/pivotalservices/canned-pks) and we thought the same as you, so we deleted the s3 bucket and re-uploaded everything after refreshing the docker image and it still failed with the same error.  I am still somewhat new to using concourse and wonder if the images got staged to a worker and didn't get refreshed even though we deleted the pipeline?  I'd be happy to jump on a zoom chat when I get back in the office on Tuesday to work through the issue.

**Comment by sparameswaran** [comment]
Another team encountered this issue earlier and got past it once they refreshed the docker image on the s3 store and refreshed the pipeline. can I know who/where you work so I can reach you in other ways?
Two things you can check:
1) Go back to the canned-pks/download-bits folder where the bits got downloaded. You should see a `nsxedgegen-nsx-t-gen-worker-v2.2-docker.tgz` file under `resources/docker` sub-directory. Run `tar tvf` on the tarball and check for `bin/govc` entries. If it has the govc under both `/usr/bin` and `/usr/local/bin`, then the tarball is latest. Verify its the same version on the s3 blobstore end. The minio datastore would have the file under the <minio-data-directory>/<bucket>/resources/docker folder. Verify on this end. 

If its not, do an upload back into minio using bom-uploader against a new bom file that only has one resource entry (reference to nsxedgegen-nsx-t-gen-worker-v2.2-docker.tgz ):

```
# MODIFIED_BOM_FILE
# Access tokens for Pivnet & my.vmware.com
pivnet_token: EDIT_ME
myvmware_user: EDIT_ME
myvmware_password: EDIT_ME
iaas: vsphere
# All combined NSX-T and PKS/Harbor Install bits listed here
bits:
- name: nsxedgegen-nsx-t-gen-worker-v2.2-docker.tgz
  contentType: application/gzip
  resourceType: docker
  tag: v2.2
  imageName: nsxedgegen/nsx-t-gen-worker
```
Refer to the above bom file when running bom upload:
```
#!/bin/bash
MODIFIED_BOM_FILE=<EDIT_ME> # EDIT ME
export TOOLS_DIR=$(dirname $BASH_SOURCE)
source $TOOLS_DIR/setup.sh

# Sample: /home/ubuntu/test-bits as the folder to refer to the downloaded bits
# Replace 'canned-pks' with different minio bucket name as needed

if [ ! -e "$TOOLS_DIR/bom-mgmt" ]; then
  echo "bom-mgmt tool not available in current folder, run $TOOLS_DIR/download-tools.sh before running this script. Exiting!"
fi

$TOOLS_DIR/bom-mgmt upload-bits --bits "${CANNED_PKS_DIR}/${DOWNLOAD_BITS_FOLDER}" \
                               --bom  "${BOM_DIR}/$MODIFIED_BOM_FILE}" \
                               --bucket "${MINIO_BUCKET}"

```
2) If the above steps are all correct, and pipeline still fails even after refresh, follow the next steps:
a) copy the `nsxedgegen-nsx-t-gen-worker-v2.2-docker.tgz`  as a new `new-nsxedgegen-nsx-t-gen-worker-v2.2-docker.tgz` on the minio s3 blobstore end directly. Or you can just re-upload using the same `bom-mgmt upload-bits` command while naming the docker image as `new-nsxedgegen-nsx-t-gen-worker-v2.2-docker.tgz` and using a custom bom file (with the `new-` prefix to the image).

Now if you do access minio using the browser (http://<minio-server>:9000/ or using the minio client interface, you should see this new file under the <bucket>/resources/docker path. 

b) Change all reference of `nsxedgegen-nsx-t-gen-worker-v2.2-docker` to `new-nsxedgegen-nsx-t-gen-worker-v2.2-docker` in the offline pipeline resources. Ensure its a global search and replace of just the `nsxedgegen-nsx-t-gen-worker-v2.2-docker` portion (so it would handle all .* or -tarball).

Re-register the modified offline pipeline with concourse and run it.  It should pull the updated docker image with new name. 

Sorry for the inconvenience.

**Comment by dsimmons5280** [comment]
We were able to get past this after deleting everything and re-uploading to make sure we had the updated docker image, it worked great.  Thanks for the quick response and detailed troubleshooting assistance.
